service: indra-technical-test-victor-zubiaga

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Query
      Resource:
        - "*"

resources:
  Resources:
    Orders:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Orders
        AttributeDefinitions:
          - AttributeName: nombreCliente
            AttributeType: S
          - AttributeName: fechaRegistro
            AttributeType: S
        KeySchema:
          - AttributeName: nombreCliente
            KeyType: HASH
          - AttributeName: fechaRegistro
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  getOrdersHttp:
    handler: src/handler.getOrderApiGateway
    events:
      - httpApi: get /orders/{nombreCliente}

  addOrderHttp:
    handler: src/handler.addOrderApigateway
    events:
      - httpApi: post /orders

plugins:
  - serverless-offline
