service: indra-integration-test

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:Scan
      Resource:
        - "*"

resources:
  Resources:
    StarWarsMovies:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: StarWarsMovies
        AttributeDefinitions:
          - AttributeName: idMovie
            AttributeType: S
        KeySchema:
          - AttributeName: idMovie
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  getMovieHttp:
    handler: src/getMovie.handler
    events:
      - httpApi: get /getMovie

plugins:
  - serverless-offline
